name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          python -m pip install -e .
          python -m pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest -q tests --maxfail=1

      - name: Upload junit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: .
